version: '3.7'
services:
  db:
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init_sqls/:/docker-entrypoint-initdb.d
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test